# Generated by Django 4.1.4 on 2022-12-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='banner',
            new_name='banner_1',
        ),
        migrations.AddField(
            model_name='product',
            name='banner_2',
            field=models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='banner_3',
            field=models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d'),
        ),
    ]
