# Generated by Django 4.1.4 on 2023-01-02 09:49

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone
import painless.models.validations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerfeedback',
            options={'get_latest_by': ['-published_at'], 'ordering': ['-published_at', 'first_name'], 'verbose_name': 'feedback', 'verbose_name_plural': 'feedbacks'},
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='feedback/%Y/%m/%d', validators=[painless.models.validations.validate_file_extension, painless.models.validations.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='first_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='last_name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='role',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
