# Generated by Django 4.1.4 on 2022-12-29 23:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'get_latest_by': ['-created'], 'ordering': ['-created', 'subject'], 'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'map', 'verbose_name_plural': 'maps'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
